(()=>{
  const START=new Date(2026,8,24),END=new Date(2027,11,31),STORE='seven-trade-v1',AUTH_STORE='seven-trade-auth-v1';
  const SITE_ID='seven-trade',OWNER_EMAIL='jordan@capital-trade.app',VIEWER_EMAIL='visual.seven@capital-trade.app';
  const SB_URL='https://chrwrhzwarusyazfkqxx.supabase.co',SB_KEY='sb_publishable_1vSobsbmds4Yz2lhb3Vi7g_0KuiFUJ0';
  const LOCAL=/^(localhost|127\.0\.0\.1)$/.test(location.hostname),money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}),dateLong=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long'}),monthLong=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}),shortDate=new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'}),weekdays=['domingo','segunda-feira','terça-feira','quarta-feira','quinta-feira','sexta-feira','sábado'];
  let state=loadLocal(),session=loadSession(),editable=LOCAL,pollTimer=null,viewMonth=new Date(START.getFullYear(),START.getMonth(),1);

  function baseState(){return{capital:10000,entries:{},withdrawals:{}}}
  function loadLocal(){try{const s=JSON.parse(localStorage.getItem(STORE))||baseState();return{capital:Number(s.capital)||10000,entries:s.entries||{},withdrawals:s.withdrawals||{}}}catch{return baseState()}}
  function loadSession(){try{return JSON.parse(localStorage.getItem(AUTH_STORE))}catch{return null}}
  function key(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
  function parseBR(v){return Number(String(v).replace(/\s/g,'').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''))||0}
  function daysBetween(a,b){return Math.ceil((b-a)/86400000)}
  function eachDay(a,b,fn){for(let d=new Date(a);d<=b;d.setDate(d.getDate()+1))fn(new Date(d))}
  function has(obj,k){return Object.prototype.hasOwnProperty.call(obj,k)}
  function summarize(){let pnl=0,withdraw=0,positive=0,negative=0,balance=state.capital;eachDay(START,END,d=>{const k=key(d),v=Number(state.entries[k]||0),w=Number(state.withdrawals[k]||0);pnl+=v;withdraw+=w;balance+=v-w;if(v>0)positive++;if(v<0)negative++});return{pnl,withdraw,positive,negative,balance}}

  function updateProjection(){
    const first=new Date(viewMonth.getFullYear(),viewMonth.getMonth(),1),last=new Date(viewMonth.getFullYear(),viewMonth.getMonth()+1,0),from=first<START?START:first,to=last>END?END:last;
    let total=0,count=0,days=0;eachDay(from,to,d=>{days++;const k=key(d);if(has(state.entries,k)){total+=Number(state.entries[k]||0);count++}});
    const average=count?total/count:0,projected=average*days,pct=state.capital?projected/state.capital*100:0;
    projectionValue.textContent=(pct>=0?'+':'')+pct.toFixed(2).replace('.',',')+'%';projectionValue.style.color=pct<0?'var(--red)':pct>0?'var(--green)':'var(--text)';
    projectionNote.textContent=count?`${count} ${count===1?'dia usado':'dias usados'} · média ${money.format(average)}/dia`:'Aguardando resultados';
    projectionFill.style.width=Math.min(100,Math.abs(pct))+'%';projectionFill.style.background=pct<0?'var(--red)':'var(--green)';
  }
  function updateSummary(){const s=summarize();totalResult.textContent=money.format(s.pnl);totalResult.style.color=s.pnl<0?'var(--red)':s.pnl>0?'var(--green)':'var(--text)';totalWithdraw.textContent=money.format(s.withdraw);positiveDays.textContent=s.positive;negativeDays.textContent=s.negative;updateProjection();updateNextSaturday()}

  function renderTable(){
    tradeRows.innerHTML='';monthLabel.textContent=monthLong.format(viewMonth).replace(/^./,c=>c.toUpperCase());const first=new Date(viewMonth.getFullYear(),viewMonth.getMonth(),1),last=new Date(viewMonth.getFullYear(),viewMonth.getMonth()+1,0);
    eachDay(first,last,d=>{if(d<START||d>END)return;const dow=d.getDay(),k=key(d),v=Number(state.entries[k]||0),w=Number(state.withdrawals[k]||0),registered=has(state.entries,k)||(dow===6&&has(state.withdrawals,k)),tr=document.createElement('tr');
      const resultInput=`<input class="money-input" inputmode="decimal" data-kind="entry" data-date="${k}" value="${has(state.entries,k)?v.toFixed(2).replace('.',','):''}" placeholder="0,00" aria-label="Resultado de ${shortDate.format(d)}" ${editable?'':'disabled'}>`;
      const withdrawInput=dow===6?`<input class="withdraw-input" inputmode="decimal" data-kind="withdrawal" data-date="${k}" value="${has(state.withdrawals,k)?w.toFixed(2).replace('.',','):''}" placeholder="0,00" aria-label="Saque de ${shortDate.format(d)}" ${editable?'':'disabled'}>`:'<span class="empty">—</span>';
      const movement=v-w,event=dow===6?'Operação + saque':'Operação diária',movementText=registered?`<span class="${movement>0?'positive':movement<0?'negative':'empty'} mono">${movement>0?'+ ':''}${money.format(movement)}</span>`:'<span class="empty">Aguardando</span>',status=registered?'<span class="status">Registrado</span>':'<span class="status">Pendente</span>';
      tr.innerHTML=`<td><div class="date-main">${shortDate.format(d)}</div><div class="date-sub">${weekdays[dow]}</div></td><td><span class="type-dot ${dow===6?'saturday':''}"><i></i>${event}</span></td><td>${resultInput}</td><td>${withdrawInput}</td><td>${movementText}</td><td>${status}</td>`;tradeRows.appendChild(tr)
    });
    tradeRows.querySelectorAll('input').forEach(el=>{el.onfocus=e=>e.target.select();el.onchange=async()=>{const target=el.dataset.kind==='withdrawal'?state.withdrawals:state.entries;target[el.dataset.date]=parseBR(el.value);await saveRemote();renderAll();toast(el.dataset.kind==='withdrawal'?'Saque sincronizado':'Resultado sincronizado')}});
    prevMonth.disabled=viewMonth<=new Date(START.getFullYear(),START.getMonth(),1);nextMonth.disabled=viewMonth>=new Date(END.getFullYear(),END.getMonth(),1);
  }
  function updateNextSaturday(){let d=new Date();if(d<START)d=new Date(START);while(d.getDay()!==6)d.setDate(d.getDate()+1);nextSaturdayDate.textContent=d>END?'Período concluído':shortDate.format(d)+' · sábado';weekBars.innerHTML='';const vals=[];for(let i=6;i>=0;i--){const x=new Date(d);x.setDate(x.getDate()-i);vals.push({label:['D','S','T','Q','Q','S','S'][x.getDay()],value:Number(state.entries[key(x)]||0)})}const max=Math.max(1,...vals.map(x=>Math.abs(x.value)));vals.forEach(x=>{const cell=document.createElement('div');cell.className='day-tick';cell.innerHTML=`<span><i style="height:${Math.max(5,Math.abs(x.value)/max*100)}%;background:${x.value<0?'var(--red)':'var(--green)'}"></i></span><small>${x.label}</small>`;weekBars.appendChild(cell)})}

  let candles=Array.from({length:64},(_,i)=>{const o=100+Math.sin(i/6)*4+(Math.random()-.5)*2,c=o+(Math.random()-.46)*4;return{o,c,h:Math.max(o,c)+Math.random()*2,l:Math.min(o,c)-Math.random()*2}}),phase=0;
  function drawMarket(){const c=marketCanvas,ctx=c.getContext('2d'),b=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=b.width*dpr;c.height=b.height*dpr;ctx.scale(dpr,dpr);const W=b.width,H=b.height,p={l:12,r:44,t:12,b:18},all=candles.flatMap(x=>[x.h,x.l]),min=Math.min(...all)-1,max=Math.max(...all)+1,yy=v=>p.t+(H-p.t-p.b)*(1-(v-min)/(max-min)),step=(W-p.l-p.r)/candles.length;ctx.clearRect(0,0,W,H);ctx.strokeStyle='#173451';for(let i=0;i<5;i++){const y=p.t+(H-p.t-p.b)*i/4;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(W-p.r,y);ctx.stroke()}candles.forEach((x,i)=>{const cx=p.l+i*step+step*.5,col=x.c>=x.o?'#00d49a':'#ff4d5a';ctx.strokeStyle=col;ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(cx,yy(x.h));ctx.lineTo(cx,yy(x.l));ctx.stroke();const y=Math.min(yy(x.o),yy(x.c)),h=Math.max(2,Math.abs(yy(x.o)-yy(x.c)));ctx.fillRect(cx-step*.26,y,Math.max(2,step*.52),h)});const last=candles[candles.length-1].c,y=yy(last);ctx.setLineDash([5,4]);ctx.strokeStyle='#6d8dff';ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(W-p.r,y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#6d8dff';ctx.fillRect(W-p.r+3,y-10,40,20);ctx.fillStyle='#fff';ctx.font='9px DM Mono';ctx.fillText(last.toFixed(1),W-p.r+6,y+3)}
  function animateMarket(){phase++;const x=candles[candles.length-1];x.c+=(Math.random()-.48)*.55;x.h=Math.max(x.h,x.c);x.l=Math.min(x.l,x.c);if(phase%32===0){const o=x.c,c=o+(Math.random()-.47)*2;candles.push({o,c,h:Math.max(o,c)+Math.random(),l:Math.min(o,c)-Math.random()});candles.shift()}drawMarket();if(phase%45===0){[idx1,idx2,idx3,idx4,idx5,idx6].forEach((el,i)=>{const v=(Math.random()*2.2-.65)*(i===3?.35:1);el.textContent=(v>=0?'+':'')+v.toFixed(2).replace('.',',')+'%';el.className=v>=0?'up':'down'});[px1,px2,px3,px4,px5,px6].forEach((el,i)=>{const raw=el.textContent.replace(/\./g,'').replace(',','.'),base=Number(raw)||100,next=base*(1+(Math.random()-.5)*.0008);el.textContent=i===3?next.toFixed(2).replace('.',','):Math.round(next).toLocaleString('pt-BR')})}requestAnimationFrame(animateMarket)}

  function toast(m){const t=document.querySelector('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}
  function renderAll(){initialCapital.value=state.capital.toFixed(2).replace('.',',');renderTable();updateSummary()}
  function setMode(){editable=LOCAL||session?.email===OWNER_EMAIL;document.body.classList.toggle('readonly',!editable);initialCapital.disabled=!editable;syncPill.classList.add('online');accessMode.textContent=LOCAL?'Prévia local':editable?'Proprietário · edição':'Sócio · visualização'}
  async function authFetch(path,opt={}){const r=await fetch(SB_URL+path,{...opt,headers:{apikey:SB_KEY,'Content-Type':'application/json',...(opt.headers||{})}});if(!r.ok)throw Error('AUTH');return r.json()}
  async function signIn(email,password){const d=await authFetch('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});return{access_token:d.access_token,refresh_token:d.refresh_token,expires_at:Date.now()+d.expires_in*1000,email:d.user.email}}
  async function validToken(){if(session.expires_at-Date.now()>60000)return session.access_token;const d=await authFetch('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:session.refresh_token})});session={access_token:d.access_token,refresh_token:d.refresh_token,expires_at:Date.now()+d.expires_in*1000,email:d.user.email};localStorage.setItem(AUTH_STORE,JSON.stringify(session));return session.access_token}
  async function api(path,opt={}){const token=await validToken(),r=await fetch(SB_URL+'/rest/v1/'+path,{...opt,headers:{apikey:SB_KEY,Authorization:'Bearer '+token,'Content-Type':'application/json',...(opt.headers||{})}});if(r.status===401){logout();throw Error('AUTH')}if(!r.ok)throw Error('SYNC');return r.status===204?null:r.json()}
  async function pullRemote(){if(LOCAL||!session||document.activeElement?.matches('.money-input,.withdraw-input,#initialCapital'))return;try{const rows=await api(`trading_dashboards?id=eq.${SITE_ID}&select=state`);if(rows?.[0]?.state){state={capital:Number(rows[0].state.capital)||10000,entries:rows[0].state.entries||{},withdrawals:rows[0].state.withdrawals||{}};localStorage.setItem(STORE,JSON.stringify(state));renderAll()}}catch{accessMode.textContent='Reconectando…'}}
  async function saveRemote(){localStorage.setItem(STORE,JSON.stringify(state));if(LOCAL)return;if(!editable)throw Error('READ_ONLY');await api(`trading_dashboards?id=eq.${SITE_ID}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({state,updated_at:new Date().toISOString()})})}
  async function start(){setMode();accessLayer.classList.add('hidden');renderAll();await pullRemote();clearInterval(pollTimer);if(!LOCAL)pollTimer=setInterval(pullRemote,5000);registerTool()}
  function logout(){session=null;editable=false;localStorage.removeItem(AUTH_STORE);clearInterval(pollTimer);accessPassword.value='';accessLayer.classList.remove('hidden')}
  function registerTool(){const context=document.modelContext;if(!editable||!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'registrar_resultado_seven_trade',title:'Registrar resultado no Seven Trade',description:'Registra resultado diário e saque de sábado no Seven Trade.',inputSchema:{type:'object',properties:{data:{type:'string'},valor:{type:'number'},saque:{type:'number'}},required:['data','valor'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute({data,valor,saque}){const d=new Date(data+'T12:00:00');if(!/^\d{4}-\d{2}-\d{2}$/.test(data)||d<START||d>END)throw Error('Escolha uma data dentro do período.');if(saque!==undefined&&d.getDay()!==6)throw Error('O saque só pode ser informado aos sábados.');state.entries[data]=valor;if(saque!==undefined)state.withdrawals[data]=saque;await saveRemote();viewMonth=new Date(d.getFullYear(),d.getMonth(),1);renderAll();return{data,valor,saque:saque||0,saldo:summarize().balance}}},{signal:lifecycle.signal})).catch(()=>{})}

  accessForm.onsubmit=async e=>{e.preventDefault();accessSubmit.disabled=true;accessError.textContent='';try{try{session=await signIn(OWNER_EMAIL,accessPassword.value)}catch{session=await signIn(VIEWER_EMAIL,accessPassword.value)}localStorage.setItem(AUTH_STORE,JSON.stringify(session));await start()}catch{accessError.textContent='Senha inválida para este painel.'}finally{accessSubmit.disabled=false}};
  logoutBtn.onclick=logout;initialCapital.onchange=async e=>{if(!editable)return;state.capital=parseBR(e.target.value);await saveRemote();renderAll();toast('Saldo bloqueado sincronizado')};prevMonth.onclick=()=>{viewMonth.setMonth(viewMonth.getMonth()-1);renderTable();updateProjection()};nextMonth.onclick=()=>{viewMonth.setMonth(viewMonth.getMonth()+1);renderTable();updateProjection()};document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.scroll).scrollIntoView({behavior:'smooth'})});todayText.textContent=dateLong.format(new Date()).replace(/^./,c=>c.toUpperCase());periodProgress.style.width=Math.max(0,Math.min(1,daysBetween(START,new Date())/daysBetween(START,END)))*100+'%';renderAll();animateMarket();if(LOCAL||session)start().catch(logout);
})();
